### ISSUE TITLE
Failed to load /opt/jboss/keycloak/modules/de/tdlabs/keycloak/extensions/keycloak-health-checks/main/module.xml

### ISSUE THREAD

**Issue by hectorj2f** [thomasdarimont/keycloak-health-checks#4]
Any idea why I get this error:

```

1
--
Caused by: java.lang.RuntimeException: org.jboss.modules.ModuleLoadException: Error loading module from /opt/jboss/keycloak/modules/de/tdlabs/keycloak/extensions/keycloak-health-checks/main/module.xml
  | at org.keycloak.provider.wildfly.ModuleProviderLoaderFactory.create(ModuleProviderLoaderFactory.java:44)
  | at org.keycloak.provider.ProviderManager.<init>(ProviderManager.java:59)
  | at org.keycloak.services.DefaultKeycloakSessionFactory.init(DefaultKeycloakSessionFactory.java:74)
  | at org.keycloak.services.resources.KeycloakApplication.createSessionFactory(KeycloakApplication.java:323)
  | at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:114)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
  | ... 28 more
  | Caused by: org.jboss.modules.ModuleLoadException: Error loading module from /opt/jboss/keycloak/modules/de/tdlabs/keycloak/extensions/keycloak-health-checks/main/module.xml
  | at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:300)
  | at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:256)
  | at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:190)
  | at org.jboss.modules.LocalModuleFinder.parseModuleXmlFile(LocalModuleFinder.java:207)
  | at org.jboss.modules.LocalModuleFinder.lambda$findModule$0(LocalModuleFinder.java:154)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at org.jboss.modules.LocalModuleFinder.findModule(LocalModuleFinder.java:154)
  | at org.jboss.modules.ModuleLoader.findModule0(ModuleLoader.java:616)
  | at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:609)
  | at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:486)
  | at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:389)
  | at org.jboss.modules.ModuleLoader.preloadExportedModule(ModuleLoader.java:401)
  | at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:442)
  | at org.jboss.as.server.moduleservice.ServiceModuleLoader.preloadModule(ServiceModuleLoader.java:149)
  | at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:387)
  | at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:282)
  | at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:270)
  | at org.keycloak.provider.wildfly.ModuleProviderLoaderFactory.create(ModuleProviderLoaderFactory.java:40)
  | ... 37 more
  | Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'de.tdlabs.keycloak:keycloak-health-checks:1.0.0-SNAPSHOT' (position: END_TAG seen ... name="de.tdlabs.keycloak:keycloak-health-checks:1.0.0-SNAPSHOT"/>... @5:84)
  | at org.jboss.modules.xml.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:955)
  | at org.jboss.modules.xml.ModuleXmlParser.parseResources(ModuleXmlParser.java:856)
  | at org.jboss.modules.xml.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:647)
  | at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:418)
  | at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:298)
  | ... 54 mor

```

**Comment by SamTheisens** [comment]
I don't know which version of KeyCloak you are on, but I would recommend you use the jboss cli to configure this extension, because KeyCloak has gone through several upgrades of WildFly and the `module.xml` example in the README is not compatible with KeyCloak 6.0.1.
This `module.xml` worked for me:
```
<?xml version='1.0' encoding='UTF-8'?>
<module xmlns="urn:jboss:module:1.1" name="com.github.thomasdarimont.keycloak.extensions.keycloak-health-checks">

    <resources>
        <resource-root path="keycloak-health-checks-4.8.3.0-SNAPSHOT.jar"/>
    </resources>

    <dependencies>
        <module name="org.keycloak.keycloak-core"/>
        <module name="org.keycloak.keycloak-services"/>
        <module name="org.keycloak.keycloak-server-spi"/>
        <module name="org.keycloak.keycloak-server-spi-private"/>
        <module name="javax.api"/>
        <module name="javax.ws.rs.api"/>
        <module name="com.fasterxml.jackson.core.jackson-core"/>
        <module name="com.fasterxml.jackson.core.jackson-databind"/>
        <module name="com.fasterxml.jackson.core.jackson-annotations"/>
        <module name="org.jboss.logging"/>
        <module name="org.infinispan"/>
        <module name="org.infinispan.commons"/>
    </dependencies>
</module>
```

**Comment by thomasdarimont** [comment]
I updated this example for the latest Keycloak version 15.0.2
